/* Deauville 2026 · V2.2.17 UX layer */
(function(){
function val(o,keys){if(!o)return '';for(const k of keys){if(o[k]!=null&&o[k]!=='')return String(o[k])}return ''}
function titleOf(o){return val(o,['title','film','name'])}
function dateOf(o){return val(o,['date','day'])}
function startOf(o){return val(o,['start','time','startTime'])}
function endOf(o){return val(o,['end','endTime'])}
function placeOf(o){return val(o,['place','venue','location','room'])}
function sameFilm(a,b){if(!a||!b)return false;const aa=normTitle(canonicalTitle(titleOf(a))),bb=normTitle(canonicalTitle(titleOf(b)));return !!aa&&!!bb&&(aa===bb||aa.endsWith(' '+bb)||bb.endsWith(' '+aa))}
function jurySessions(){return DATA?(Array.isArray(DATA.jury)?DATA.jury:[]).concat(Array.isArray(DATA.juryExtra)?DATA.juryExtra:[]):[]}
function juryFilmSessions(s){return jurySessions().filter(j=>sameFilm(j,s))}
function exactJurySession(s){if(!s)return null;return juryFilmSessions(s).find(j=>dateOf(j)===dateOf(s)&&startOf(j)===startOf(s))||null}
function personalPlanEntry(s){return s?plan.find(p=>p.sessionId===s.id)||null:null}
function plannedFilmSession(s){if(!s)return null;const e=exactJurySession(s);if(e)return null;const j=juryFilmSessions(s)[0];if(j)return j;const p=plan.find(x=>x.sessionId!==s.id&&sameFilm(x,s));return p?DATA.sessions.find(x=>x.id===p.sessionId)||p:null}
function plannedFilmLabel(s){const p=plannedFilmSession(s);return p?`<span class="badge green">🎬 SÉANCE DÉJÀ PRÉVUE</span><span class="filmPlanRef">Séance prévue : ${dateLabel(dateOf(p))} · ${startOf(p)}</span>`:''}
function installClear(){const w=document.querySelector('.searchWrap'),i=document.getElementById('search');if(!w||!i)return;let b=w.querySelector('.searchClear');if(!b){b=document.createElement('button');b.type='button';b.className='searchClear';b.setAttribute('aria-label','Effacer la recherche');b.textContent='×';b.onclick=e=>{e.preventDefault();e.stopPropagation();i.value='';i.dispatchEvent(new Event('input',{bubbles:true}))};w.appendChild(b)}b.style.display=i.value?'flex':'none'}
const oci=window.conflictItems;if(typeof oci==='function'){window.conflictItems=function(s){const e=exactJurySession(s);return oci(s).filter(x=>!(e&&(x.source==='jury'||x.source==='juryExtra')&&sameFilm(x,s)))}}window.conflict=function(s){return typeof window.conflictItems==='function'&&window.conflictItems(s).length>0}
const ocl=window.compatibilityLabel;if(typeof ocl==='function')window.compatibilityLabel=function(s){if(exactJurySession(s))return '<span class="status planned">✓ SÉANCE JURY AU PLANNING · '+dateLabel(dateOf(s))+' · '+startOf(s)+'</span>';return ocl(s)};
const oss=window.sessionStatusHtml;if(typeof oss==='function')window.sessionStatusHtml=function(s){if(exactJurySession(s))return '<div class="wishStatus planned">📅 SÉANCE JURY · OBLIGATOIRE · DANS TON PLANNING<br><span class="filmPlanRef">Séance prévue : '+dateLabel(dateOf(s))+' · '+startOf(s)+'</span></div>';const c=window.conflictItems(s),p=personalPlanEntry(s);if(c.length)return '<div class="wishStatus bad">⚠️ NON COMPATIBLE</div>';if(p)return '<div class="wishStatus planned">✓ SÉANCE DANS TON PLANNING<br><span class="filmPlanRef">Séance prévue : '+dateLabel(dateOf(s))+' · '+startOf(s)+'</span></div>';const f=plannedFilmLabel(s);return f||'<div class="wishStatus good">✓ COMPATIBLE</div>'};
const oes=window.explorerCard;if(typeof oes==='function')window.explorerCard=function(s){let h=oes.apply(this,arguments);const e=exactJurySession(s),p=personalPlanEntry(s);h=h.replace(/<span class="badge gold">JURY · DÉJÀ AU PLANNING<\/span>/g,'');const b=e?'<span class="badge green">📅 DANS MON PLANNING</span><span class="badge gold">JURY · OBLIGATOIRE</span>':p?'<span class="badge green">📅 DANS MON PLANNING</span>':plannedFilmLabel(s);if(h.includes('ecBadges'))h=h.replace('<div class="ecBadges">','<div class="ecBadges">'+b);else h='<div class="exactJuryPatch">'+b+'</div>'+h;return h};
const oos=window.openSession;if(typeof oos==='function')window.openSession=function(id,blocked=false,backStart=null,backEnd=null,backSessionId=null){const s=DATA&&DATA.sessions.find(x=>String(x.id)===String(id)),e=s&&exactJurySession(s),p=s&&personalPlanEntry(s);let back='';if(backSessionId){back=`<button class="backBtn" onclick="openSession('${backSessionId}',false,${backStart!==null?Number(backStart):'null'},${backEnd!==null?Number(backEnd):'null'},null)">← Retour à la séance précédente</button>`}else if(backStart!==null&&backEnd!==null){back=`<button class="backBtn" onclick="openFree(${Number(backStart)},${Number(backEnd)})">← Retour aux séances compatibles</button>`}if(e){openModal(`${back}<div class="section">JURY · OBLIGATOIRE</div><h2>${esc(s.title)}</h2><div class="info">📅 ${dateLabel(s.date)}<br>🕘 ${s.start}–${s.end}<br>📍 ${esc(s.place)}</div><div class="notice jury">📅 DANS TON PLANNING<br><strong>JURY · SÉANCE OBLIGATOIRE</strong><br><span class="filmPlanRef">Séance prévue : ${dateLabel(s.date)} · ${s.start}</span></div><p>Cette séance est déjà au planning Jury. Elle ne doit pas être ajoutée une seconde fois.</p>`);return}if(p){openModal(`${back}<div class="section">MON PLANNING</div><h2>${esc(s.title)}</h2><div class="info">📅 ${dateLabel(s.date)}<br>🕘 ${s.start}–${s.end}<br>📍 ${esc(s.place)}</div><div class="notice">📅 CETTE SÉANCE EST DÉJÀ DANS TON PLANNING<br><span class="filmPlanRef">Séance prévue : ${dateLabel(s.date)} · ${s.start}</span></div><button class="btn primary" onclick="removeSession('${p.id}')">Retirer cette séance du planning</button>`);return}return oos.apply(this,arguments)};
const oas=window.addSession;if(typeof oas==='function')window.addSession=function(id,force){const s=DATA&&DATA.sessions.find(x=>String(x.id)===String(id)),p=s&&personalPlanEntry(s);if(p){removeSession(p.id);return}if(s&&exactJurySession(s)){toast('Cette séance Jury est déjà au planning');return}return oas.apply(this,arguments)};
let compatibleOnly=false;function isCompatibleForFilter(s){return !!s&&(!!exactJurySession(s)||!window.conflict(s))}const osm=window.sessionMatches;if(typeof osm==='function')window.sessionMatches=function(s){return osm(s)&&(!compatibleOnly||isCompatibleForFilter(s))};
function installFilter(){const f=document.querySelector('.filters');if(!f)return;let r=f.querySelector('.compatibilityRow');if(!r){r=document.createElement('div');r.className='filterRow compatibilityRow';const b=document.createElement('button');b.type='button';b.id='compatibleFilter';b.className='planningFilter';b.onclick=()=>{compatibleOnly=!compatibleOnly;render()};r.appendChild(b);f.appendChild(r)}const b=r.querySelector('#compatibleFilter');b.textContent='✓ Compatible avec mon planning';b.setAttribute('aria-pressed',compatibleOnly);b.classList.toggle('active',compatibleOnly)}
function markExactJuryCards(){document.querySelectorAll('[data-session]').forEach(card=>{const id=card.getAttribute('data-session'),s=DATA&&DATA.sessions&&DATA.sessions.find(x=>String(x.id)===String(id)),exact=s&&exactJurySession(s);card.classList.toggle('exactJuryCard',!!exact);let mark=card.querySelector('.exactJuryMark');if(mark)mark.remove()})}
function enhance(){installClear();installFilter();markExactJuryCards();const v=document.querySelector('.version');if(v)v.textContent='V2.2.17'}
const or=window.render;if(typeof or==='function')window.render=function(){const r=or.apply(this,arguments);enhance();return r};
document.addEventListener('click',function(e){const card=e.target.closest&&e.target.closest('[data-session]');if(!card)return;const s=DATA&&DATA.sessions.find(x=>String(x.id)===String(card.dataset.session));if(s&&exactJurySession(s)){e.preventDefault();e.stopImmediatePropagation();openModal(`<div class="section">JURY · OBLIGATOIRE</div><h2>${esc(s.title)}</h2><div class="info">📅 ${dateLabel(s.date)}<br>🕘 ${s.start}–${s.end}<br>📍 ${esc(s.place)}</div><div class="notice jury">📅 DANS TON PLANNING<br><strong>JURY · SÉANCE OBLIGATOIRE</strong><br><span class="filmPlanRef">Séance prévue : ${dateLabel(s.date)} · ${s.start}</span></div><p>Cette séance est déjà au planning Jury. Elle ne doit pas être ajoutée une seconde fois.</p>`)}} ,true);
const style=document.createElement('style');style.textContent=`.searchWrap{position:relative}.searchWrap input{padding-right:42px}.searchClear{position:absolute;right:8px;top:50%;transform:translateY(-50%);width:30px;height:30px;border:0;border-radius:50%;background:#eee9df;color:#191815;font-size:24px;line-height:1;align-items:center;justify-content:center;cursor:pointer;opacity:.8;padding:0}.planningFilter{width:100%;border:1px solid var(--line);border-radius:10px;background:#fff;color:var(--ink);padding:9px 8px;font-size:11px;cursor:pointer;text-align:left;white-space:nowrap;flex:1 1 0;min-width:0}.planningFilter.active{font-weight:700;border-color:var(--green);box-shadow:inset 0 0 0 1px var(--green)}.compatibilityRow{margin-top:7px}.filterRow select{flex:1 1 0;width:0;min-width:0}.filmPlanRef{font-size:9px;color:var(--muted);align-self:center}.ecBadges .badge{display:inline-flex;align-items:center;gap:3px}.exactJuryCard{background:#fff!important;box-shadow:0 0 0 2px #c9a227!important}.exactJuryMark{display:none}.exactJuryPatch{margin-bottom:6px}.backBtn{display:block;margin:0 0 12px;padding:0;border:0;background:none;color:var(--ink);font-size:12px;font-weight:700;cursor:pointer;text-align:left}`;document.head.appendChild(style);if(document.readyState!=='loading')enhance();else document.addEventListener('DOMContentLoaded',enhance)
})();